// PHASE 1 SCAFFOLD — UNBUILT, UNTESTED. See ../../README.md before touching
// this on a Windows box.
#pragma once
// Generated by cppwinrt from VirtualPrinterTask.idl during the build (see
// Generated Files\ under the project's intermediate output) — defines the
// VirtualPrinterTaskT<D, ...> CRTP base the factory_implementation struct
// below needs. Must be included before that struct is declared.
#include "Tasks.VirtualPrinterTask.g.h"

#include <winrt/Windows.ApplicationModel.Background.h>
#include <winrt/Windows.Devices.Printers.h>
#include <winrt/Windows.Graphics.Printing.Workflow.h>

namespace winrt::Tasks::implementation
{
    // Implements the WinRT class the AppxManifest.xml virtual-printer
    // extension activates (EntryPoint="Tasks.VirtualPrinterTask") when a
    // print job is submitted to the "Stirling PDF" queue.
    // VirtualPrinterTaskT here is the generated alias (from
    // Tasks.VirtualPrinterTask.g.h) for VirtualPrinterTask_base<D, I...>,
    // which wires up implements<D, Tasks::VirtualPrinterTask, IBackgroundTask,
    // I...> and GetRuntimeClassName() for us. Inheriting winrt::implements<>
    // directly (an earlier version of this file did) compiles but omits
    // Tasks::VirtualPrinterTask from the interface list, which breaks the
    // generated projection constructor in Tasks.VirtualPrinterTask.g.cpp
    // (C2665: no overloaded function could convert all the argument types) —
    // found by actually building this on Windows, not by reading docs.
    struct VirtualPrinterTask : VirtualPrinterTaskT<VirtualPrinterTask>
    {
        VirtualPrinterTask() = default;

        void Run(winrt::Windows::ApplicationModel::Background::IBackgroundTaskInstance const& taskInstance);

    private:
        // fire_and_forget, not void: the body needs co_await for the async
        // storage/PDL-conversion calls. m_taskDeferral.Complete() at the end
        // is what actually signals completion to the background task host;
        // see the .cpp for the get_strong() lifetime note.
        winrt::fire_and_forget OnVirtualPrinterDataAvailable(
            winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowVirtualPrinterSession const& sender,
            winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowVirtualPrinterDataAvailableEventArgs const& args);

        winrt::Windows::ApplicationModel::Background::BackgroundTaskDeferral m_taskDeferral{ nullptr };
        winrt::Windows::Devices::Printers::IppPrintDevice m_printDevice{ nullptr };
    };
}

namespace winrt::Tasks::factory_implementation
{
    struct VirtualPrinterTask : VirtualPrinterTaskT<VirtualPrinterTask, implementation::VirtualPrinterTask>
    {
    };
}
